### PR TITLE
Css changes

### PR DESCRIPTION
**Pull request by lil5**
These are purely visual css changes

### CODE REVIEW

**Comment by averageflow** [comment]
Nice work man, checkout also what I have been changing in the CSS of v1.1.3

**Comment by lil5** [comment]
@averageflow Please don't change the location of the static files too often.

**Comment by averageflow** [comment]
@lil5 Ja Wohl! But you will agree this is indeed a better location right? Also easier to setup linting for Go and for others

**Comment by lil5** [comment]
Will make more focused PR's using the changes made here

**Pull request closed without merging**
